### ISSUE TITLE
node_modules/react-circular-menu/styles.css doesn't exist

### ISSUE THREAD

**Issue by LivesleyWA** [9inpachi/react-circular-menu#1]
styles.css is missing

**Comment by 9inpachi** [comment]
Okay I just noticed. Sorry, I seemed to have not specified `styles.css` in package.json `files`. I'll republish the package in some minutes.

**Comment by 9inpachi** [comment]
Should be there now, try installing the latest version with `npm install react-circular-menu@latest`.

**Comment by LivesleyWA** [comment]
Thanks - works now

**Comment by 9inpachi** [comment]
Thanks for using the package and pointing out the issue. :)
