### ISSUE TITLE
Can one set custom images as icons?

### ISSUE THREAD

**Issue by rovashan** [9inpachi/react-circular-menu#11]
I would like to use a custom image as an icon.

**Comment by 9inpachi** [comment]
Yes, that should work. Any of the direct children of `<CircleMenu>` will
become menu items and will circle around the menu toggle.

**Comment by rovashan** [comment]
I'm able to add an image to CircleMenuItem but not CircleMenu. Is there a way to change the main menu icon to an image as well?

**Comment by 9inpachi** [comment]
Could you share the code? You are right, the way it works now is that there is a `CircleButton` in each `CircleMenuItem`. What you can do is overwrite the default styles by specifying a `className` for `CircleMenuItem`. Something like:

```tsx
<CircleMenuItem className="class-with-overwritten-styles">
  <img />
</CircleMenuItem>
```

> Is there a way to change the main menu icon to an image as well?

Yes. you can use this prop in `CircleMenu` for this: https://github.com/9inpachi/react-circular-menu#menutoggleelement-reactelement

**Comment by 9inpachi** [comment]
If you have a use case that isn't working with the suggestions above., let me know, and I can update the code for the menu.

**Comment by rovashan** [comment]
Brilliant thanks. The menuToggleElement  prop works.
This is my code if anyone needs to do the same.

` <CircleMenu
	startAngle={-90}
	rotationAngle={360}
	itemSize={2}
	radius={5}
	menuToggleElement={<img src="https://source.unsplash.com/user/c_v_r/100x100" alt="Placeholder"/>}
	rotationAngleInclusive={false}
>
	<CircleMenuItem
		onClick={() => alert("Clicked the item")}
		tooltip="Email"
		tooltipPlacement={TooltipPlacement.Right}
	>
		<img src="https://source.unsplash.com/user/c_v_r/100x100" alt="Placeholder"/>
	</CircleMenuItem>
	<CircleMenuItem tooltip="Help">
		<img src="https://source.unsplash.com/user/c_v_r/100x100" alt="Placeholder"/>
	</CircleMenuItem>
</CircleMenu>`

**Comment by 9inpachi** [comment]
Cool, thanks for sharing. It seems that you wanted to have an image for the menu toggle.

Is it fine to close the issue then?

**Comment by rovashan** [comment]
Yes fine to close, thanks.
