### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by lucasartsfr** [9inpachi/react-circular-menu#12]
Just install the module with dependencies and use the Example in Demo page. Here is the error : 

Server Error
SyntaxError: Unexpected token 'export'

This error happened while generating the page. Any console logs will be displayed in the terminal window.

Call Stack
<unknown>
file:///D:/Project/node_modules/react-circular-menu/dist/index.js (1)

Working With NextJS, Last version of NPM and NodeJS. The problem seam to be Next and ES6 ? Do You have Idea how to fix this ? Tried : 
```
experimental: {
    transpilePackages: ['react-circular-menu','styled-components'],
  }
```
in node.config but it's experimental sor maybe there is another solution ?

Found a Solution With Dynamic Import : 

import dynamic from 'next/dynamic';

const CircleMenu = dynamic(() => import('react-circular-menu').then(mod => mod.CircleMenu), { ssr: false });
const CircleMenuItem = dynamic(() => import('react-circular-menu').then(mod => mod.CircleMenuItem), { ssr: false });
const TooltipPlacement = dynamic(() => import('react-circular-menu').then(mod => mod.TooltipPlacement), { ssr: false });

**Comment by 9inpachi** [comment]
I think this is because you are importing the component on a server-side rendered page. And it seems ES6 imports don't work on the server-side in Next.js.

I could try fixing it by having an entry point for commonjs as well. For now, I think the dynamic import is a good enough solution.

Thanks for reporting this.

**Comment by lucasartsfr** [comment]
Thanks for answer ! Ineed it's a good solution.

Also, with Next we use <Link> instead of <a> or <button>

Would be a good functionnality if we can choose the HTMLnode for MenuItem wrapper, because without href it's a Button, and With href it's a Link, and having <Link> englobing <a> or <button> is bad for DOM and SEO.

Regards,

**Comment by 9inpachi** [comment]
Hey @lucasartsfr, do you have your project on GitHub by any chance?

**Comment by lucasartsfr** [comment]
Hello, I do, for my website : https://github.com/lucasartsfr/LucasArtsFr-website

Used transpil package from NextJS 13+ instead of dynamic import. Seams to work, but maybe not the best way 

https://github.com/lucasartsfr/LucasArtsFr-website/blob/main/next.config.js

I Forked your project to remove button and replace by div (button with block child's is not good, but that is the only edit)

**Comment by lucasartsfr** [comment]
Also tried to edit the code to allow NextLink instead of simple a or button but did not find a way to do it ahah (not good with typescript)

So I need to use useRouter from next with event

**Comment by 9inpachi** [comment]
> I Forked your project to remove button and replace by div (button with block child's is not good, but that is the only edit)
> Also tried to edit the code to allow NextLink instead of simple a or button but did not find a way to do it ahah (not good with typescript)
> So I need to use useRouter from next with event

That's a good point. The `CircleMenu` has a [prop for defining custom element](https://github.com/9inpachi/react-circular-menu#menutoggleelement-reactelement). I can try doing something similar for the `CircleMenuItem`. You should be able to use a custom element then. But I am not sure if I have the time to do that now — will keep it in mind for a future version.

**Comment by lucasartsfr** [comment]
Yeah don't worry, love Circular Menu and just wanted some improvement for my project ahah ! But would be a great feature to allow custom element

**Comment by 9inpachi** [comment]
#13 fixes the original issue. I added support for CommonJS and it seems to work out of the box with your repo without the need to specify the package in `transpilePackages` in `next.config.js`.

**Comment by lucasartsfr** [comment]
Oh great ! I'll check that ! 🙏
