### ISSUE TITLE
Is there a way to have this tied to onContextMenu instead of onClick?

### ISSUE THREAD

**Issue by jasonmcleod** [9inpachi/react-circular-menu#14]
Just found this library today and I'm really impressed with how easy it was to add it into my game. I'm wondering if there's already a way to specify which event will call the menu up, or if it's hard coded to use onClick.

I'll dive a bit deeper and see if I can spot this myself but I figured I would go ahead and ask.

Thanks!

**Comment by 9inpachi** [comment]
That's a very interesting use-case. I didn't write this with that kind of usage in mind, so the `CircleMenu` handles all the menu toggling logic inside it.

However, I think it should be simple if I introduce a prop named `active` and use it to decide if the menu toggle is active or not. That way, the prop can be used as state outside the component and updated accordingly.

**Comment by 9inpachi** [comment]
A new prop `open` is added to the `CircleMenu` component.

https://github.com/9inpachi/react-circular-menu#open-boolean

**Comment by jasonmcleod** [comment]
Awesome! I'll have a look. Thanks for working on it!
