### ISSUE TITLE
Avoid having two circular menus active at the same time

### ISSUE THREAD

**Issue by HugoMito** [9inpachi/react-circular-menu#15]
Hello,
Thanks for building this very useful package. 👌🏼

Is there a way to avoid having two circular menus active at the same time (controlled components), in order to avoid this scenario?
![image](https://github.com/9inpachi/react-circular-menu/assets/65476864/c54438cd-c459-4b53-820d-58be52e33c71)

Thanks in advance!

**Comment by 9inpachi** [comment]
Hi, I will add a `menuActive` prop that will make the component controlled.

**Comment by HugoMito** [comment]
Awesome 👌🏼
Looking forward for that new version.
Thanks!

**Comment by 9inpachi** [comment]
The new version v2.4.0 is published to npm. It adds a new prop `open` to the `CircleMenu` component which can be used to define the initial toggle state of the menu or control it through the parent state.

Let me know if it works for you.

Thanks for using the package. :)

**Comment by HugoMito** [comment]
I tested @2.4.0, but I think it is not working.

I set open={false}, but as you can see on the image, once I clicked the CircularMenu, it simply opened, but it should not, right? or am I misunderstanding the usage of the open key?

![image](https://github.com/9inpachi/react-circular-menu/assets/65476864/b4478349-fdff-4c02-aae4-4f6e378f733c)

**Comment by 9inpachi** [comment]
That is as intended. The component still has an internal state for toggling
the menu. The `open` prop can be used to control the toggle state in
addition to the internal state.

Do you want to use it in a way where the parent component completely
controls the toggle state and there is no internal state?

**Comment by HugoMito** [comment]
The main goal is: Do not open another menu, if there is one menu active.
---

This is what I was thinking, I hope makes sense, and whatever option is easier for you: 

Have in mind the two Circular Menus (Tools and Monitor) from the images above.

### Scenario 1:
- The user clicks the Tools circular menu, it opens the menu and sets an object as follows toolsMenuOpen = True using onMenuToggle prop.
- Then, having the Tools circular menu active, the user clicks the Monitor circular menu, it won't open because the open prop is set to false using toolsMenuOpen value, as follows: open={!toolsMenuOpen}

### Scenario 2
- The user clicks the Tools circular menu, it opens the menu and sets an object as follows monitorMenuOpen = false using onMenuToggle prop.
- That will cause the Monitor circular menu to close, using open prop, no matter what.

If you have a better way... welcome!
Thanks!

**Comment by 9inpachi** [comment]
This will be something that has to be controlled from the parent component. One circle menu component shouldn't know of any other circle menu component's state.

What you can do is define an `menuOpen` state for the two menus you have. Now since we have the `open` prop, we can use the `onMenuToggle` prop of one component to change the `menuOpen` state of the other menu.

Here's a component that does this.

```tsx
const TestComponent: FC = () => {
  const [menuOpen1, setMenuOpen1] = useState(false);
  const [menuOpen2, setMenuOpen2] = useState(false);

  return (
    <>
      <CircleMenu
        open={menuOpen1}
        onMenuToggle={(toggleState) => {
          // If menu is opening, then set it's state (`menuOpen1`) to true
          // and the other menu's state (`menuOpen2`) to false.
          if (toggleState) {
            setMenuOpen1(true);
            setMenuOpen2(false);
          }
        }}
        startAngle={0}
        rotationAngle={90}
      >
        <CircleMenuItem tooltip="Info">
          <InfoIcon />
        </CircleMenuItem>
      </CircleMenu>
      <CircleMenu
        open={menuOpen2}
        onMenuToggle={(toggleState) => {
          // If menu is opening, then set it's state (`menuOpen2`) to true
          // and the other menu's state (`menuOpen1`) to false.
          if (toggleState) {
            setMenuOpen1(false);
            setMenuOpen2(true);
          }
        }}
        startAngle={0}
        rotationAngle={90}
      >
        <CircleMenuItem tooltip="Email">
          <MailIcon />
        </CircleMenuItem>
      </CircleMenu>
    </>
  );
};
```

Here's a working GIF that uses the same logic.

![react-circular-menu-two-menus](https://github.com/9inpachi/react-circular-menu/assets/36920441/5861aa1e-8afd-409b-99ce-40be038b016a)

**Comment by HugoMito** [comment]
Awesome! 👌🏼
Now the Circle menus are working fine!
You may close this issue.
Thanks!
