### ISSUE TITLE
How to Center CircleMenuItems with CircleMenu

### ISSUE THREAD

**Issue by HugoMito** [9inpachi/react-circular-menu#16]
Hello again,
Thanks for building and customizing this very useful/nice package. 👌🏼

Is there a way to center CircleMenuItems with CircleMenu, in order to avoid this scenario?
![image](https://github.com/9inpachi/react-circular-menu/assets/65476864/58613f92-f90f-4fe8-81b2-f5d7323df927)

This is my menuToogleElement:
![image](https://github.com/9inpachi/react-circular-menu/assets/65476864/4cd7cdde-2fff-4e7f-b001-2a3672bc27be)

#homeEstimatesBorder {
  ...
  height: 9.5rem,
  width: 9.5rem
}

Thanks in advance!

**Comment by 9inpachi** [comment]
Hi @HugoMito, this has been fixed and the package has been published. Please update to v2.4.1.

**Comment by HugoMito** [comment]
Awesome! 👌🏼
It works just fine.
Thanks a lot!!!
