### ISSUE TITLE
你好👋,请问有没有vue版本

### ISSUE THREAD

**Issue by HHANG52** [9inpachi/react-circular-menu#17]
看着项目，美观好看，自己的vue项目想用到，不知道有没有vue组件呢。

**Comment by 9inpachi** [comment]
不，不幸的是没有 Vue 组件。 使菜单项放置在菜单周围的核心代码位于https://github.com/9inpachi/react-circular-menu/blob/master/src/CircleMenu/CircleMenu.tsx#L75-L94。 这些是正确放置它们的菜单项样式https://github.com/9inpachi/react-circular-menu/blob/master/src/CircleMenuItem/StyledCircleMenuItem.ts#L19-L26。

注：这是用谷歌翻译的。

**Comment by HHANG52** [comment]
好的，感谢回复。（Okay, thank you for your reply.）
