### ISSUE TITLE
Can't resolve 'react/jsx-runtime'

### ISSUE THREAD

**Issue by romrg** [9inpachi/react-circular-menu#2]
Using react-circular-menu 2.0.0, I have now this build issue:

ERROR in ./node_modules/react-circular-menu/dist/CircleButton/CircleButton.js
Module not found: Error: Can't resolve 'react/jsx-runtime' in './node_modules/react-circular-menu/dist/CircleButton'

It was fine with 1.0.2 (React.createElement calls were generated in distrib files).

**Comment by 9inpachi** [comment]
What version of React are you using? I tested on React 17+ so it might be related to that. There is not particular import like that in the TS file but I will check in the build. Thanks for pointing it out.

**Comment by romrg** [comment]
I'm still using React 16.14 for now but it is not an issue. It is related to tsconfig - https://www.typescriptlang.org/tsconfig#jsx. It is a choice - keep emitting _jsx calls in distrib files but users must migrate to react 17, or keep the compatibility with React 16.X.
