### ISSUE TITLE
Document peer dependencies

### ISSUE THREAD

**Issue by romrg** [9inpachi/react-circular-menu#3]
styled-components is declared as a dev dependency. Thus, to use react-circular-menu 2.0.0, we have to also declare this dependency in our project if it does not already use it.

**Comment by romrg** [comment]
It is better to not declare material-ui or styled-composants as normal dependencies to give more flexibility to users regarding the versions. Peer dependencies should be fine. I was thinking about a section in the README to highlight this requirement, especially for styled-components you just introduced.

**Comment by 9inpachi** [comment]
`styled-components` has a FAQ about this here: https://styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library

I think it's not optimal to have the dependency on `@material-ui/core` because the package just uses tooltip from it.
