### ISSUE TITLE
Remove dependency to material-ui

### ISSUE THREAD

**Issue by 9inpachi** [9inpachi/react-circular-menu#7]

**Comment by jsduffy** [comment]
Yeah, this would be nice (or updating to the latest material-ui if not).

**Comment by devdev-dev** [comment]
Same for me - I am using chakra-ui not mui.

**Comment by 9inpachi** [comment]
Sorry for the long delay. Just released v2.3.0 with a custom tooltip implementation and removed dependency to `@material-ui/core`.
